### ISSUE TITLE
At least a 'request_host' or a 'request_path' must be specified

### ISSUE THREAD

**Issue by madhur** [PGBI/kong-dashboard#105]
I am getting this error in the kong dashboard 1.3.0 docker image. This used to work fine while creating the API. Has anything changed?

**Comment by PGBI** [comment]
Kong Dashboard doesn't generate errors by itself: it returns and displays errors returned by Kong. Maybe you have upgraded to a version of Kong in which there is a new constraint on request_host/request_path.
