### ISSUE TITLE
Is it possible to manage upstreams?

### ISSUE THREAD

**Issue by smartwjw** [PGBI/kong-dashboard#106]
[Ring Balancer](https://getkong.org/docs/0.10.x/loadbalancing/#ring-balancer) was add since v0.10,
I am looking forward to manage upstream targets in kong-dashboard, thanks in advance.

**Comment by Asa-Dong** [comment]
+1  it's useful. tks.

**Comment by PGBI** [comment]
Managing upstreams is now possible.
