### ISSUE TITLE
Unable to access API configured in Kong in web application

### ISSUE THREAD

**Issue by nabanita18** [PGBI/kong-dashboard#110]
I am unable to access my API configured in Kong through the web application. In Kong server(Linux machine) using curl command I am able to access the API without any issue. But while i try to access the same API in the web application its giving connection timed-out err. I am new to Kong, so not sure where I am going wrong.

works fine: 
curl -i -X GET http://*.*.*.*:8000/API_<name>/Controller?user=1 --header "apikey:***" 

web application api url not working:
http://*.*.*.*:8000/API_<name>/Controller?user=1&apikey:***

Also, I am not able to access kong dashboard at http://localhost:8080.

Can someone help me on this please?

**Comment by PGBI** [comment]
What is the version of kong-dashboard you're using? How did you install it? How do you start it?

**Comment by nabanita18** [comment]
That's correct, it should be apikey=***.
The issue was with the port 8000, it was blocked by firewall.
