### ISSUE TITLE
Add SSL to API?

### ISSUE THREAD

**Issue by 109163101120** [PGBI/kong-dashboard#120]

**Comment by ernsheong** [comment]
Maybe this is the issue: https://github.com/Mashape/kong/issues/1663#issuecomment-251791175

**Comment by ernsheong** [comment]
Oops, looking at my error logs at `/usr/local/Cellar/kong/0.11.0/logs` (macOS)

```
2017/08/31 05:06:24 [error] 47395#0: *54353 [lua] responses.lua:107: handler(): ERROR: invalid input syntax for uuid: "kong-cert" (5129), client: 127.0.0.1, server: kong_admin, request: "POST /certificates HTTP/1.1", host: "kong:8001", referrer: "http://localhost:8080/"
```

Looks like the ID field should be left blank...

**Comment by PGBI** [comment]
I have no idea what this issue is about. There is no description. Closing.
