### ISSUE TITLE
Kong-Dashboard support for Kong 0.11.x

### ISSUE THREAD

**Issue by kkindaface** [PGBI/kong-dashboard#125]
I know V2 does not support Kong 0.11.x and it is expected to work only until 0.10.x. I am opening this issue/ticket to see if there is an update coming for 0.11.x

**Comment by PGBI** [comment]
Yep, working on it. Will be ready in the coming weeks

**Comment by gottfrois** [comment]
I'm using kong-dashboard v2 with kong 0.11 and it works well for now. I'm curious to see what are the incompatibility issues?

**Comment by kkindaface** [comment]
I don't think the new ui shows the new attributes supported by 0.11 while
adding any new API, it still shows the request_path. And also the
strip_request_path has changed in 0.11


Similar things when adding/modifying some plugins.

Adding consumers/credentials is working as expected.

On Oct 9, 2017 08:03, "Pierre-Louis Gottfrois" <notifications@github.com>
wrote:

I'm using kong-dashboard v2 with kong 0.11 and it works well for now. I'm
curious to see what are the incompatibility issues?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PGBI/kong-dashboard/issues/125#issuecomment-335185487>,
or mute the thread

**Comment by PGBI** [comment]
Kong 0.11.x is now supported with Kong Dashboard v3.0.0
