### ISSUE TITLE
Cant Get Access Dashboard From My Browser To Remote Kong Server

### ISSUE THREAD

**Issue by TomReddish-MVC** [PGBI/kong-dashboard#128]
I have read through most, if not all of the issues surrounding the setup of kong dashboard on a remote server (#23, #59, #41). I have not found a concrete example of setting all of this up as well so I may have some things configured incorrectly. Either way what I have is:

**Run Docker Kong** 
docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=password" --expose 8000 -p 8000  --expose 8001 -p 8001:8001 --expose 8443 --expose 8444 kong:0.10

**Run Docker Kong Dashboard**
docker run -d --name kong-dashboard -p 8080:8080 pgbi/kong-dashboard:v2

**Kong Api Created:**
curl -X POST http://localhost:8001/apis/ --data 'name=kong-dashboard' --data "upstream_url=http://localhost:8001" --data "uris=/kong"

**Basic Auth Added To Api**
curl -X POST http://localhost:8001/apis/kong-dashboard/plugins --data 'name=basic-auth'

**Consumer Created**
curl -X POST http://localhost:8001/consumers --data 'username=kong-dashboard-user'

**Basic Auth Added To Consumer**
curl -X POST http://localhost:8001/consumers/kong-dashboard-user/basic-auth --data 'username=user' --data "password=password"

**This is where I am not sure if I need or not and tried with and with out but Cors Plugin**
curl -X POST http://localhost:8001/apis/kong-dashboard/plugins --data 'name=cors' --data "config.methods=GET, POST" --data "config.credentials=true" --data "config.headers=Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Auth-Token" --data "config.origins=http://x.x.x.x"

Now if i go to my browser and type in http://x.x.x.x:8080 it takes me to the kong-dashboard setup screen which seems to be working. However I can not get the save to work. For the kong node url I tried:

http://x.x.x.x:8000/kong - _this did not work_
http://x.x.x.x:8001 - _this worked but only because I published the 8001 port on the kong container and opened 8001 on the firewall but I obviously do not want this to be open for production_

What am I doing wrong that the is making _http://x.x.x.x:8000/kong_ not work?

**Comment by PGBI** [comment]
First: you should not need Cors. Requests to Kong aren't directly made by your browser, but are forwarded to a proxy backend server running in the kong-dashboard container.

Now, when you say:
> http://x.x.x.x:8000/kong - this did not work

What's x.x.x.x? If you used 127.0.0.1 or localhost, it won't work. Because it the context of the kong-dashboard container, it designates the kong-dashboard container.

x.x.x.x should be the gateway IP of your kong-dashboard container, or your computer IP on your network.

You can also linking the kong container when starting kong-dashboard:
```
docker run -d --name kong-dashboard -p 8080:8080 --link kong:kong pgbi/kong-dashboard:v2
```
And then input http://kong:8000/kong once on kong-dashboard config screen.

**Comment by TomReddish-MVC** [comment]
@PGBI So x.x.x.x is the public IP address of my digital ocean droplet. So should I be using that? Also by linking the kong container to the kong dashboard container can I still use http://kong:8000/kong?

**Comment by TomReddish-MVC** [comment]
@PGBI Thank you! It worked by linking the kong container to the kong dashboard and using http://kong:8000/kong as the node url.
