### ISSUE TITLE
Basic Authentication support

### ISSUE THREAD

**Issue by Toilal** [PGBI/kong-dashboard#13]
Using nginx as a frontend before Kong, I've introduced a basic authentication on Admin API.

It would be great to support such authentication inside kong-dashboard.

**Comment by PGBI** [comment]
Basic auth support added with release 1.1.0

**Comment by SpeciaLeePhp** [comment]
@PGBI first i am very excited to hear the news that authentication will be added in 1.1.0,and i wanna know when the stable version 1.1.0 will release? my company needs the new feature eagerly,thx.

**Comment by majintao** [comment]
support rbac?
