### ISSUE TITLE
what is the Admin API URL of kongDash ??

### ISSUE THREAD

**Issue by bybab** [PGBI/kong-dashboard#133]
i'm use ubuntu 16.04 release.

I tried this.
a running Kong gateway. https://getkong.org/install/
nodejs and npm.

and,
kong start -> ok
kong-dashboard start -> 
    Launching webserver
    Server is running on port 8080

npm version => 5.5.1
node version => 6.11.5
kong version => 0.11.1
kong-dashboard version => 2.x

In KongDash, I enter the admin api url, and I get an error saying that it can not connect even with localhost and my local ip (192.168.x.x). Why?

**Comment by PGBI** [comment]
Admin API Url depends on your setup, we can't really debug this for you. I would check if the port is correct, and if you can access yourself that admin API by trying to reach it directly with your browser.
