### ISSUE TITLE
Ability to sort api's

### ISSUE THREAD

**Issue by smaquois123** [PGBI/kong-dashboard#135]
I've got a lot of api's and finding the one I'm interested in is a bit tedious.  Sorting by api name would be most helpful.  Kinda surprised it's not already there.

**Comment by PGBI** [comment]
While I agree this would be a nice feature, I'm kinda of surprised you do not make a PR to implement it.

**Comment by PGBI** [comment]
So, this is still not possible: Kong doesn't offer any way to sort results in its "list APIs" endpoint.
https://getkong.org/docs/0.11.x/admin-api/#list-apis
