### ISSUE TITLE
Ability to use environment variables to configure kong dashboard

### ISSUE THREAD

**Issue by mwisner** [PGBI/kong-dashboard#136]
With kong 3.0 now using cli commands for initial configuration, using docker it's required to use a command in the docker-compose file to correctly configure kong.

However when the kong admin endpoint is secured using basic auth this means we must store the username and password in the git repo in order for kong-dashboard to work correctly. 

While we do want to avoid storing any access information in the repo, the bigger problem is when the same application is used in multiple environments & applications, and we don't want to use the same kong management access info for everyone. It's not possible as far as I know to override commands in docker-compose files per-environment, and we would like to avoid having to manage multiple branches and whatnot with specific differences.

Personally, I think the most ideal solution would be to allow kong-dashboard to consume env vars as well as command line options.

**Comment by PGBI** [comment]
If you use docker, you can start your kong dashboard container using your env variables:
```
docker run --rm -p 8080:8080 pgbi/kong-dashboard start \
  --kong-url http://kong:8001 \
  --kong-username ${USERNAME_ENV_VARIABLE} \
  --kong-password ${PASSWORD_ENV_VARIABLE}
```

As for docker-compose, you can include environment variables in a docker-compose file `command` argument.
https://docs.docker.com/compose/environment-variables/
