### ISSUE TITLE
Add image to Docker Hub

### ISSUE THREAD

**Issue by geoand** [PGBI/kong-dashboard#14]
It would be great if the image built from this repository could be added to the Docker Hub.
It would eliminate the Git checkout step and enable the use of standard docker work-flows.

The process is fully described [here](https://docs.docker.com/docker-hub/github/)

**Comment by PGBI** [comment]
I added the image to docker hub. Kong dashboard can now be installed and run with the following command:
```
docker run -d -p 8080:8080 pgbi/kong-dashboard
```

**Comment by geoand** [comment]
Awesome! Thanks!
