### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid Version: 0.12.0rc2

### ISSUE THREAD

**Issue by qinxingnet** [PGBI/kong-dashboard#143]
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Invalid Version: 0.12.0rc2 

why ? not supply ? what~ time ?

**Comment by PGBI** [comment]
I've no idea what you are trying to tell me. Please follow the issue template.
