### ISSUE TITLE
kong 0.12

### ISSUE THREAD

**Issue by xvipservice** [PGBI/kong-dashboard#147]
when suport kong 0.12

**Comment by PGBI** [comment]
no roadmap. When I have time.

**Comment by ermazi** [comment]
+1

**Comment by uzengo** [comment]
+1

**Comment by peeyush1234** [comment]
+1

**Comment by javega** [comment]
@PGBI So no more kong-dashboard  :(

**Comment by asantos2000** [comment]
+1

**Comment by mwz** [comment]
+1

**Comment by christianlafleur** [comment]
+1

**Comment by PGBI** [comment]
done thanks to @peeyush1234

**Comment by hanhui870** [comment]
who need 0.12 now ,  can try https://github.com/zhujingfa/kong-dashboard, not full tested. so I will not open an pull request.

0.12 mainly change:
This is fixed:
⚠️ To reduce confusion, the /upstreams/:upstream_name_or_id/targets/ has been updated to not show the full list of Targets anymore, but only the ones that are currently active in the load balancer. To retrieve the full history of Targets, you can now query /upstreams/:upstream_name_or_id/targets/all. The /upstreams/:upstream_name_or_id/targets/active endpoint has been removed. Thanks @hbagdi for tackling this backlog item! #3049

This is not, can use delete sheme.
Two new endpoints, /healthy and /unhealthy can be used to manually bring upstream Targets up or down, as part of the new health checks feature of the load balancer. #3096
