### ISSUE TITLE
Kong 0.13 support

### ISSUE THREAD

**Issue by zhouzhuojie** [PGBI/kong-dashboard#160]
## Issue summary

https://github.com/Kong/kong/blob/master/CHANGELOG.md

Kong 0.13 adds Services and Route, really nice to see if kong-dashboard can support it.

And most of the things are still supported in 0.13, like API. Maybe we can also extend v3 to support kong 0.13.

**Comment by ddy86** [comment]
@zhouzhuojie Really nice！

**Comment by aroundthecode** [comment]
+1 👍

**Comment by lsj3210** [comment]
+1

**Comment by mwz** [comment]
+1

**Comment by davidqhr** [comment]
+1

**Comment by tronghieu** [comment]
+1

**Comment by youxixin888** [comment]
+1

**Comment by Quinn-Mei** [comment]
+1

**Comment by airpig2011** [comment]
+1

**Comment by 0x5459** [comment]
+1

**Comment by lsj3210** [comment]
+1

**Comment by ndruw2** [comment]
+1

**Comment by ganeshs** [comment]
I see a pull request #161 raised. Can it be merged if it meets the requirement?

**Comment by tomodutch** [comment]
+1

**Comment by minikiller** [comment]
+1

**Comment by yulix** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by naturallight** [comment]
+1

**Comment by withlin** [comment]
+1

**Comment by Inuyasha-Monster** [comment]
+1

**Comment by PGBI** [comment]
I heard you guys, just be patient, I have a job too :)

Locking that conversation for now, to avoid being email-spammed by all the "+1". Sorry.

**Comment by PGBI** [comment]
Kong-Dashboard 3.3.0 was just released and brings partial support to Kong 0.13.

**Comment by PGBI** [comment]
Support to Routes & Services added to Kong-dashboard 3.4.0
