### ISSUE TITLE
When can we support the 0.14 version

### ISSUE THREAD

**Issue by Fury76** [PGBI/kong-dashboard#176]
Hi
when can we support the 0.14 version. and starting with 0.13.0, the API entity was deprecated.
when can we support the  new Routes and Services entities

thanks~

**Comment by leoterry-ulrica** [comment]
the same issue
This version of Kong dashboard doesn't support Kong v0.14 and higher

**Comment by kepkin** [comment]
It seems like this won't gonna happen. I'm not a frontend guy, so I'm not capable to fork and contribute to this project. However I've found a _react-admin_ project from marmelab guys that does a lot of boilerplate, so I've written an alternative. 

It doesn't support everything, and I'm not a frontend developer at all.. So any help would be great. Please check this out.

https://github.com/kepkin/kong-react-admin

**Comment by PGBI** [comment]
Kong-dashboard v3.5.0 was just released with support for Kong 0.14.
