### ISSUE TITLE
Kong dashboard 3.5.0 version doesn't support Kong v0.15 and higher.

### ISSUE THREAD

**Issue by lanyuange** [PGBI/kong-dashboard#198]
Kong dashboard 3.5.0 version doesn't support Kong v0.15 and higher.

**Comment by illyaMs** [comment]
Seems to be duplicate for https://github.com/PGBI/kong-dashboard/issues/194

**Comment by PGBI** [comment]
Fixed with #199

**Comment by nileshb30** [comment]
How to resolve Kong dashboard 3.5.0 version doesn't support Kong v0.15 and higher.I am trying installing another version of kong but it can not install.How to resolve this.I install the kong 1.1.1 latest version and kong-dashboard 3.6.0.But the dashboard is not showing all the tab it only showing the HOME,PLUGINS and SERVICES tab.How can i get remaining tab in the kong dashboard.
