### ISSUE TITLE
community push

### ISSUE THREAD

**Issue by sinzone** [PGBI/kong-dashboard#2]
lmk when you feel confortable enough in sharing it and we'll include it in the next kong newsletter

**Comment by PGBI** [comment]
Thanks I would appreciate that!

I tested it thoroughly before releasing the version 1.0.0. I haven't found any bug, appart from the one linked to this Kong issue https://github.com/Mashape/kong/issues/720 . So I think it's ready to be shared.

**Comment by sinzone** [comment]
ok - will go out with the next newsletter in a month or so.

**Comment by PGBI** [comment]
:+1:
