### ISSUE TITLE
Feature Req: http-proxy support

### ISSUE THREAD

**Issue by noogen** [PGBI/kong-dashboard#23]
I'm having a tough time setting up what was recommended in issue #22.  Default Kong Admin CORS support doesn't seem to play well with basic-auth plugin, especially across different browsers.  I can't seem to override it with the CORS plugin either.  Would it be possible to get http-proxy support for this dashboard?

Example implementation/mod (expressjs):  https://github.com/niiknow/kong-dashboard
Dashboard deployed:  http://dock1.brickinc.net:8080/ (demo basic-auth security)
I setup Kong API endpoint as recommended in issue #22 and docker environment variable KONG_URL=http://kong-api:8001/kong

As an example where kong-api is on dock4 host.  Also disabled docker port mapping to 8001: http://dock4.brickinc.net:8001 (disabled) vs http://dock4.brickinc.net:8000 and http://dock4.brickinc.net:8443
Kong Rancher Docker Compose: https://github.com/trybrick/community-catalog/blob/master/templates/kong/0/docker-compose.yml

Documentation/Docker:  https://hub.docker.com/r/brickinc/kong-dashboard/

Of course, this feature may prevent the SPA to be statically hosted only scenario.  Alternative solution would be to use aerobatic service ( https://www.aerobatic.com/) which provide free static hosting and added proxy backend to overcome CORS.

Another use-case for the proxy is with Docker management like Rancher/TumTum.  Point everything to Rancher internal IPs and firewall/enable the dashboard on a needed basis.

*\* My issue may just be a configuration issue or it may be a Kong issue.  I do not know.  It may be that we need better documentation on how to set it up.  As I noted before, if CORS is working correctly, there are great benefit for this App to be statically hosted only.  This way, everyone can use the same App to access their API from anywhere.   Excellent work by the way!  Thanks for sharing and keep up the great work!

**Comment by PGBI** [comment]
I have a hard time deciding myself if it is better or not to have requests being proxied by a backend service. As you said, there are great benefits in having the app be statically hosted only.

As I said in #22 I currently don't have any time to implement this kind a feature right now, it involves a lot of code rewriting. But if anybody is willing to make a PR (and provide support for it afterwards) I'll be happy to merge it.

Now, I know it is possible to manage Kong admin API behind Kong gateway and basic-auth plugin. I did it myself and it works. I'll come up with a more detailed documentation to explain how to set it up correctly.

**Comment by PGBI** [comment]
PR #59 solved this.
