### ISSUE TITLE
Cannot associate plugin with specific consumer

### ISSUE THREAD

**Issue by chefArchitect** [PGBI/kong-dashboard#27]
Hi Pierre,

thanks for the great tool!  There is an issue with associating a plugin with a specific consumer instance.  This issue  #26 mentioned the same effect and you closed it, but I think it's a bug.

This is the payload from my local installation sent to the Kong server when I try to add a Rate Limiter plugin to a specific consumer:

`
{
  api_id: "c2828feb-5605-4d9e-cd38-1298861a68f9",
  name: "rate-limiting",
  config: {
    minute: "10"
  }
}
`
What is missing from the payload is the 'consumer_id' attribute which - according to the Kong API - is supported but optional.  I guess that's the whole problem.

**Comment by PGBI** [comment]
Ok, I must not have fully understood the issue #26 . Thanks for clarifying it. Will have a look.

**Comment by PGBI** [comment]
I was not able to reproduce the problem: I can see the consumer_id in the body payload of the request when trying myself.

- sorry for asking, but are you correctly selecting a consumer in the "Apply to" select?
<img width="556" alt="capture d ecran 2016-03-03 a 10 45 25" src="https://cloud.githubusercontent.com/assets/6191583/13490487/43cd2272-e12d-11e5-86f7-ed6057fefb1d.png">

- what browser are you using? Which version of kong? which version of kong-dashboard?
- could you provide screenshots maybe?

Thanks!

**Comment by chefArchitect** [comment]
Hi Pierre,

thanks for the feedback!  It just occurred to me that the latest Docker image I downloaded yesterday doesn't include the 'Apply to' field shown in your screenshot.  Looks like the image contains a previous version.  Can you verify?

**Comment by chefArchitect** [comment]
Sorry Pierre, my bad :(  Finally realized that certain plugins display this specific option.  Closing the issue - sorry for the hassle!  Thanks again for your time.

**Comment by PGBI** [comment]
No pb. But since you are the second person raising an issue about this (after #26 ), I believe the UI is not that intuitive. If you have any suggestions about this, don't hesitate to share them!

**Comment by chefArchitect** [comment]
Well, I guess that adding a 'Heads Up' paragraph in the description green box - stating that the 'Apply to' mapping works for specific plugins - would do the trick ;)  Other than that, the tool works great!  Keep up the good work.
