### ISSUE TITLE
Cannot Build on Ubuntu.

### ISSUE THREAD

**Issue by crr** [PGBI/kong-dashboard#29]
When attempting to install Kong Dashboard, I've been getting the following error with no sense of how to get through it.

```
> kong-dashboard@1.1.0 install /usr/local/lib/node_modules/kong-dashboard
> node ./bin/kong-dashboard build

Downloading javascript librairies...

/usr/local/lib/node_modules/kong-dashboard/lib/kong-dashboard.js:21
            if (err) throw err;
                           ^
Error: Command failed: 
Error: EACCES, permission denied '/root/.config/configstore/bower-github.yml'
You don't have access to this file.
```
The building fails on this line: ```node ./bin/kong-dashboard build```.

I've attempted a few fixes online, including changing the permissions of the .config folder, installing bower and the other dependancies globally, separately of the dashboard, but still to no avail.

Any help is greatly appreciated.

**Comment by vl4d** [comment]
Since you installed it globally, you may need to run the build command as a root user or use sudo.

**Comment by PGBI** [comment]
Hi, sorry for the late answer. I believe you were running `npm install -g` as root, which you should not.

If it doesn't work when running the command as a regular user, you should probably fix your npm permissions: https://docs.npmjs.com/getting-started/fixing-npm-permissions
