### ISSUE TITLE
"@/all" on gitter channel and google groups

### ISSUE THREAD

**Issue by sinzone** [PGBI/kong-dashboard#3]
you may want to announce it there

**Comment by PGBI** [comment]
Will do!
Also, I noticed there is a list of resources in the README.md file of Kong repository. Would you be ok if I submit a PR for adding Kong dashboard?

**Comment by sinzone** [comment]
yeah

**Comment by sinzone** [comment]
are you planning on maintaining and keeping it up to date?

**Comment by PGBI** [comment]
Absolutely. Since I'm using Kong for managing APIs, I'll need this dashboard to remain functional.
