### ISSUE TITLE
kong-dashboard also got 'kik'ed - concat was used, no longer available

### ISSUE THREAD

**Issue by DonMartin76** [PGBI/kong-dashboard#32]
See here: kong-dashboard is using the npm package `concat`, which was also part of the many modules "azer" unpublished a day ago or so:

https://gist.githubusercontent.com/azer/db27417ee84b5f34a6ea/raw/50ab7ef26dbde2d4ea52318a3590af78b2a21162/gistfile1.txt

This causes `npm install` to fail.

**Comment by PGBI** [comment]
crap. Do you know any module equivalent to `concat`?

**Comment by PGBI** [comment]
nevermind, kong-dashboard is not using concat although it's listed in the dependencies. Will remove it.

**Comment by PGBI** [comment]
Should be good now
