### ISSUE TITLE
unable load Kong-dashboard

### ISSUE THREAD

**Issue by Abhi2277** [PGBI/kong-dashboard#34]
Hello,

I have installed the Kong-Dashboard and i am getting the following error when i tried to load the webpage using http://127.0.0.1:8080,

Cannot GET /

On the server, i see that the web services are running. Below is the screen shot of the same,

Launching webserver
serving /var/kong-dashboard/public on port 8080

request your inputs on the same. 

Thanks for your support.

**Comment by PGBI** [comment]
Sorry for the late answer... If you get "Cannot GET /" when accessing the page, it means kong-dashboard install failed. How did you install it? Did you get any error?

**Comment by Abhi2277** [comment]
No worries. I installed it on another machine and got it working. Thanks for your support.

**Comment by arsdehnel** [comment]
@Abhi2277 maybe you can close this if this was just a one-time error?  I just was going through open issues to see if someone already filed something related to one I'm having and see that this one seems to be resolved.

**Comment by PGBI** [comment]
dup of #30
