### ISSUE TITLE
unable to login to dashboard

### ISSUE THREAD

**Issue by hmadala5** [PGBI/kong-dashboard#35]
Hi,
           I am unable to open the dash board page after using 
http://127.0.0.1:8080
http://localhost:8080

I could see authentication required dialog popping up for username and pwd

I could see the container running fine and its installed fine
Any help is appreciated

regards,
Hema R

**Comment by jimmypk** [comment]
Try with your LAN IP instead of this local ip.

**Comment by DonMartin76** [comment]
Are you running docker on an actual local machine (Linux), or are you doing this using Mac or Windows? In the latter cases you will usually have to access the container service using the docker machine IP. In my case that's `http://192.168.99.100:8080`.
