### ISSUE TITLE
kong-dashboard start fails on local install

### ISSUE THREAD

**Issue by RRMoelker** [PGBI/kong-dashboard#36]
When not installing globally the server will not come up.

Steps taken:

```
npm install kong-dashboard
npm install grunt
```

(notice another issue, grunt must also be installed)

Next when trying to run the local version of the dashboard I get an error:

```
$ ./node_modules/.bin/kong-dashboard start -p 8000
Launching webserver
<project_root>/node_modules/kong-dashboard/lib/kong-dashboard.js:98
        throw err;
        ^

Error: Command failed: /bin/sh -c <project_root>/node_modules/kong-dashboard/lib/../node_modules/.bin/serve --port 8000 --no-logs --no-icons <project_root>/node_modules/kong-dashboard/lib/../public
/bin/sh: <project_root>/node_modules/kong-dashboard/lib/../node_modules/.bin/serve: No such file or directory

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
```

Notice I replaced my project root absolute path with: `<project_root>`. And my node version is as follows:

```
$ node --version
v5.5.0
```

**Comment by RRMoelker** [comment]
The culprit is the "hardcoded" relative path on the line https://github.com/PGBI/kong-dashboard/blob/master/lib/kong-dashboard.js#L33

This does not work for the flat dependencies in the newer node versions

**Comment by PGBI** [comment]
In older version of Kong-Dashboard, there were no guidance on which version(s) of node you needed because it wasn't tested.

This has been improved with Kong-Dashboard v3 for which you should not get this kind of error as long as you use node >= 6.
