### ISSUE TITLE
Doesn't work with Kong 0.8.0 because tagline in that version is 'kong' lowercase

### ISSUE THREAD

**Issue by chrisfarnham** [PGBI/kong-dashboard#38]
Spun up the new Kong 0.8.0 to kick the tires. Couldn't get dashboard to recognize the node as a node. Quick review of the code tells me that it's trying to match the 'tagline' attribute returned a GET to the admin panel but can't because the case of Kong in the tagline has been changed.

Recommend a less brittle way of assessing if is, in fact, a Kong node.

**Comment by jfirehammer-credibly** [comment]
I just hit this too. Are they any other 0.8.0 issues you have hit?

**Comment by chrisfarnham** [comment]
I patched my local source and have been using it with no problems other
than the one i reported.

Christopher Farnham
chris.farnham@gmail.com

**Comment by jimmypk** [comment]
How to patch it @chrisfarnham

**Comment by PGBI** [comment]
Fixed on version 1.1.2. Thanks @chrisfarnham for reporting this.
