### ISSUE TITLE
Menu Options

### ISSUE THREAD

**Issue by TomDaviesUK** [PGBI/kong-dashboard#45]
I'm using Kong 0.6.0. 

I've installed the dashboard and can successfully access my Kong deployment.

But none of the top right menus work ("! not found"). Is there a minimum compatibility with Kong for the dashboard?

**Comment by PGBI** [comment]
I'm using Kong 0.6.* myself, and it's compatible.

Could you open your browser console and let me know if you get any errors when clicking the top menu links?

**Comment by TomDaviesUK** [comment]
Ah! It works in Explorer, not so much Chrome...I'll close the issue and run with Explorer.
