### ISSUE TITLE
NodeJS issue

### ISSUE THREAD

**Issue by Kenovo** [PGBI/kong-dashboard#47]
Hello
i have a probleme with nodejs when i try to install kong-dashboard, could you please spicify what version of nodejs kong-dashboard need to work correctly 

Thank you

**Comment by nimboya** [comment]
What operating system are you working with?

**Comment by Suhwi** [comment]
When I installed kong dashboard on ubuntu 12.04, I got an error like something related to nodejs.. The error message.. like as "failed to fetch from registry: xxxxxx"...
At last, I solved the issue like below....

> sudo apt-get purge nodejs npm
> sudo apt-get install -y python-software-properties python g++ make software-properties-common
> sudo add-apt-repository ppa:chris-lea/node.js
> sudo apt-get update
> sudo apt-get install nodejs

**Comment by nimboya** [comment]
Good good.

**Comment by PGBI** [comment]
It should work with node >= 0.8.0
