### ISSUE TITLE
Can't install with npm on Ubuntu 14.04

### ISSUE THREAD

**Issue by rbrtmrtn** [PGBI/kong-dashboard#48]
When I `npm install -g kong-dashboard` on Ubuntu 14.04 I'm getting the error: `Failed at the kong-dashboard@1.1.2 install script 'node ./bin/kong-dashboard build'.`.

Here is the error log: https://gist.github.com/rbrtmrtn/5651d493715de406e86acff89301cdfc

Thanks!

**Comment by PGBI** [comment]
This was probably caused by node/npm versions not supported by Kong-Dashboard. Kong-Dashboard v3 does support node 6 to 8.
