### ISSUE TITLE
started the kong dashboard but localhost:8080 is getting failed

### ISSUE THREAD

**Issue by Ansar1628** [PGBI/kong-dashboard#51]
When i tried to hit the below url
_http://localhost:8080/_  getting below output 
_Cannot GET /_  with 404 status code

launched kong-dashboard by running npm start

 npm start

> kong-dashboard@1.1.2 start /opt/kong_poc/kong-dashboard
> node ./bin/kong-dashboard start

Launching webserver
serving /opt/kong_poc/kong-dashboard/public on port 8080

**Comment by JIgneshThakker** [comment]
I am also getting same problem in my machine.

**Comment by kaybinwong** [comment]
does anybody know how to fix this issue?

**Comment by yezhwi** [comment]
I am also getting same problem, May not compile successfully，If successful compilation, generates the "public" directory

The problem solving process is as follows

1.to file /usr/local/kong-dashboard/lib/kong-dashboard.js  add " --allow-root" , var cmd = __dirname + "/../node_modules/.bin/bower install --allow-root";

2./usr/local/kong-dashboard# npm install 
 then throw error "npm WARN lifecycle kong-dashboard@1.1.2~install: cannot run in wd %s %s (wd=%s) kong-dashboard@1.1.2 node ./bin/kong-dashboard build /usr/local/kong-dashboard", 
so npm install --unsafe-perm

3.test  curl localhost:8080 , then return to the home page

**Comment by PGBI** [comment]
@yezhwi you get "cannot run in wd %s %s" because npm won't run install script if you're running as root. If you have permissions issues when running `npm install -g kong-dashboard` you need to fix your npm permissions => https://docs.npmjs.com/getting-started/fixing-npm-permissions
