### ISSUE TITLE
Plugins broken with Kong 0.9.0

### ISSUE THREAD

**Issue by wshirey** [PGBI/kong-dashboard#52]
When selecting plugin, all values in drop down are set to 'true'. Probably related to breaking change migration.

![screenshot 2016-08-25 10 27 55](https://cloud.githubusercontent.com/assets/1452263/17975307/c9c618ec-6aae-11e6-822e-7d04bdfe0f31.png)

**Comment by kamran-rahmani** [comment]
I have the same issue as well.

**Comment by PGBI** [comment]
Thanks for reporting. Haven't had time yet to update kong-dashboard to be compatible with Kong 0.9.

**Comment by maxtuzz** [comment]
Fixed this in my pull: https://github.com/PGBI/kong-dashboard/pull/54
