### ISSUE TITLE
Plugins don't show

### ISSUE THREAD

**Issue by kamran-rahmani** [PGBI/kong-dashboard#53]
Hi,

I installed the dashboard on my localhost (through both Docker and npm) but whe ntry to configure , nothing shows up except a list of all "true"s. 

![screen shot 2016-08-25 at 5 40 10 pm](https://cloud.githubusercontent.com/assets/7017192/17990481/03caca4c-6aeb-11e6-9a37-8700dce65d87.png)

Any idea what might be wrong?

**Comment by thenayr** [comment]
https://github.com/PGBI/kong-dashboard/issues/52

**Comment by PGBI** [comment]
Duplicate - Closing

**Comment by maxtuzz** [comment]
Fixed in my PR: https://github.com/PGBI/kong-dashboard/pull/54
