### ISSUE TITLE
Clickjacking

### ISSUE THREAD

**Issue by saithala** [PGBI/kong-dashboard#58]
We are using Kong-Dashboard as a UI tool for Kong. As part of our internal network scan, it was identified that this app has a clickjacking vulnerability.  The solution was to return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response
Can anyone please point out how to quickly add this ?  In particular the following page was identified as vulnerable.

http://localhost:8080/html/config.html

ping @PGBI

**Comment by PGBI** [comment]
@saithala I pushed a fix for that, thanks for reporting it. It will be shipped with the next release.
