### ISSUE TITLE
Kong Login

### ISSUE THREAD

**Issue by BMLande** [PGBI/kong-dashboard#61]
i am beginner to this,,,
what type of kong node url added when we start kong UI.
from where i get it?
i setup my container for Kong and cassandra
http://172.17.0.3 is my Kong container ip which i now using it rises error said"can't acess Kong Node with this url/port"

**Comment by Ansar1628** [comment]
you have to specify port as well
try using http://172.17.0.3:8001

**Comment by BMLande** [comment]
Thanks ansar it worksffor me
