### ISSUE TITLE
unable to load kong-dashboard on centos7

### ISSUE THREAD

**Issue by zhujinhu21** [PGBI/kong-dashboard#62]
![1234](https://cloud.githubusercontent.com/assets/4327149/21071239/824d9988-bed5-11e6-95ac-61555ef05075.png)
after npm start  ,access http://localhost:8080/ 
i can't see web manage, only js css navgiation.

**Comment by hos7ein** [comment]
i have same problem on centos 7.2 and only display "Cannot GET /" on screen!
how  can i fix this problem?

tnx

**Comment by PGBI** [comment]
@zhujinhu21 If the public folder doesn't contain the index.html file, it means something went wrong when building the app on `npm install`. Can you try again with the last version of kong dashboard?

**Comment by hos7ein** [comment]
after download dashboar src , go to src dir  and run this command : 

> #  cd kong-dashboard

and then run this command : 

> # npm install

then run this command : 

> # npm start -- -p 9091 -a admin=hos7ein

after that open web browser with this address : 

> http:[server-ip]:9091


after enter user and password i see "Not Found" msg on page!

all of output  is here : 
http://paste.fedoraproject.org/513633/37403148/

tnx

**Comment by PGBI** [comment]
@hos7ein Looks like `npm install` only downloads npm packages, without running the install script defined in package.json. 

What's your version of npm (`npm -v`)?
Can you please try running `npm run install` after `npm install`?

**Comment by hos7ein** [comment]
@PGBI tnx man
run successful 👍 

all of output : 

http://paste.fedoraproject.org/513649/14828410/


tnx ;)
