### ISSUE TITLE
how to enable basic auth in a docker based installation

### ISSUE THREAD

**Issue by w0w** [PGBI/kong-dashboard#67]
I have installed kong-dashboard using docker image and i want to put a basic auth for accessing dashboard, what is docker equivalent of 

```
set kong-dashboard-name=admin&& set kong-dashboard-pass=password&& kong-dashboard start
````

**Comment by PGBI** [comment]
This way:
```
docker run -p 8080:8080 pgbi/kong-dashboard npm start -- -a admin=password
```

**Comment by w0w** [comment]
I tried with above command and auth is not implemented.

**Comment by PGBI** [comment]
@w0w It will ask you credentials when attempting to browse kong dashboard: You should see an authentication popup.

As for the docker image, maybe aren't you using the last version of it? Can you try:
```
docker pull pgbi/kong-dashboard
docker run -p 8080:8080 pgbi/kong-dashboard npm start -- -a admin=password
```

**Comment by w0w** [comment]
@PGBI Works, my docker image was outdated. Thanks a lot.
