### ISSUE TITLE
Kong-Dashboard no longer works in my setup

### ISSUE THREAD

**Issue by rwillard** [PGBI/kong-dashboard#69]
I'm running kong and kong-dashboard in a kubernetes cluster, and I can no longer connect with my kong node URL. The URL hasn't changed and did work previously. On docker-hub there's only images since version 1.2.1 from 10 days ago. I forked the repo and trie to manually build the image from the 1.1.2 release, but that fails

`The command '/bin/sh -c apk --update add ca-certificates git python build-base &&    npm install && npm run install &&    apk del ca-certificates git python build-base &&    rm -rf /var/cache/apk/*' returned a non-zero code: 1`

Can you add that image back on docker-hub so I can use kong-dashboard again?

**Comment by PGBI** [comment]
Unfortunately, before 1.2.1 release docker images weren't tagged properly. You can see all the images that were built here => https://hub.docker.com/r/pgbi/kong-dashboard/builds/
I guess you want to pull one of the image with the "latest" tag that was built a few months ago. However I'm not sure how this can be done.

The previous Dockerfile (before v 1.2.1) wasn't working anymore. I guess something must have changed with the mhart/alpine-node it was built from. That's why I rewrote it.

What's exactly your issue with the latest docker image? Is kong-dashboard not starting? Or does it start but can't reach your kong node?

**Comment by rwillard** [comment]
kong-dashboard starts, but it can't reach my kong node. It so happens that I still have an older version of kong-dashboard running in one of my namespaces that I can use, but only until k8s pulls down a newer version. When using the newer version I get a can't connect to kong error, but using the same url string in the older image works fine.

**Comment by rwillard** [comment]
I got the v1.1.2 image hosted on docker-hub now if you wanted to get it into your repo. https://hub.docker.com/r/robertgwillard/kong-dashboard/tags/

**Comment by BetaGrumm** [comment]
Also seeing this happen. We hadn't deployed our instance of kong/dashboard in a while. When I redeployed the environment, using the latest tag on kong-dashboard, the dashboard could no longer connect to the node. No other changes.

**Comment by itsandrew** [comment]
Same issue here. Tried reverting back to earlier v1.1.2 image, but also does not seem to resolve.

**Comment by PGBI** [comment]
If you start the dashboard with `docker run -p 8080:8080 pgbi/kong-dashboard` (without `-d`), do you see any error output in the console when trying to connect the dashboard to Kong?

Same question for the browser console, any output that could help debugging?

Last thing I have in mind, when the dashboard attempts to make a call to Kong API, there is a 5s timeout after which it will display "something wrong happened". Do you guys get the error right away or after 5s?

**Comment by itsandrew** [comment]
Just tried the above, but no error output in the terminal. 

For the browser console, here is what I see after immediately receiving the "Can't connect to Kong server." message (no 5s delay).

angular.min.js:93 GET http://localhost:8080/proxy/ 400 (Bad Request)

(anonymous) @ angular.min.js:93
m @ angular.min.js:89
l @ angular.min.js:86
(anonymous) @ angular.min.js:119
$eval @ angular.min.js:133
$digest @ angular.min.js:130
$apply @ angular.min.js:133
(anonymous) @ angular.min.js:254
dispatch @ jquery.min.js:3
g.handle @ jquery.min.js:3

**Comment by BetaGrumm** [comment]
I can confirm that rwillards image of v1.1.2 (https://hub.docker.com/r/robertgwillard/kong-dashboard/tags/) is working with my implementation.

I'll stick with that and occasionally check back for a new version.

**Comment by PGBI** [comment]
@itsandrew can you share the kong node url you are setting up in your dashboard?

**Comment by rwillard** [comment]
The problem I was having is the same as @itsandrew, GET http://localhost:8080/proxy/. No matter what URL I put in, it would end up doing a GET request to the hosted IP and adding /proxy/ to the end.

**Comment by itsandrew** [comment]
@PGBI http://localhost:8001

**Comment by amehat** [comment]
I have the same problem. The url http: // localhost: 8001 / proxy returns : 
`{
     "Message": "Not found"
}`

**Comment by user974256** [comment]
Looks like commit 8447c19b5b2368cfd177d7688a11452ec5c98e39 introduced the `/proxy` endpoint. Would be nice if somebody could have a look at all the problems this commit introduced and possibly revert it.

I'm seeing the same problems as described above, making the dashboard unusable.

**Comment by hnq90** [comment]
I got same issue even on `master` branch.

**Comment by shavo007** [comment]
+1

Cant use the dashboard with this issue.

**Comment by user974256** [comment]
I had to downgrade to continue using the dashboard, using `docker pull digitalism/kong-dashboard:v1.1.2-branch` which is built using a dockerfile from `https://github.com/digitalism/kong-dashboard`

**Comment by amehat** [comment]
Cant use the dashboard.
I just tried with digitalism/kong-dashboard: v1.1.2-branch, and I always get 'Bad Request' with the url /proxy.

**Comment by hnq90** [comment]
I still got 500 error...

![](http://pix.toile-libre.org/upload/original/1487643578.png)

**Comment by vkill** [comment]
@amehat [Ref](https://github.com/PGBI/kong-dashboard/issues/40#issuecomment-282622591)
