### ISSUE TITLE
Specify kong node url in config param?

### ISSUE THREAD

**Issue by JustinFarris** [PGBI/kong-dashboard#75]
We're running kong-dashboard in a docker container, and due to the network config, the default kong node url of "http://localhost:8001" is unreachable from the kong-dashboard container. Is it possible to specify the kong node admin URL in a docker parameter or the app config so that it defaults to what we specify?

**Comment by PGBI** [comment]
Let's say you gave the name "kong" to the docker container hosting your kong node. Then you can start the kong-dashboard container this way:
```
docker run -p 8080:8080 --link kong:kong pgbi/kong-dashboard
```

Then, when browsing kong dashboard config page on localhost:8080/#/config, you must input `http://kong:8001` for the kong node url.

**Comment by JustinFarris** [comment]
Thanks for that. We were actually looking for a way to default that value so that we don't need to input anything in the UI to tell it which kong host to connect to. I think we've found a solution using "--net=host" when we start the docker container.
