### ISSUE TITLE
request_host is an unknown field

### ISSUE THREAD

**Issue by linonetwo** [PGBI/kong-dashboard#83]
When adding an API, it shows ```request_host is an unknown field``` and ```request_path is an unknown field```, maybe Kong changes its API fields?

**Comment by linonetwo** [comment]
https://github.com/Mashape/kong/pull/1970

**Comment by liangmeng1986** [comment]
是不是升级kong到了0.10.0版本

**Comment by JeryChen** [comment]
When to support kong-0.10.x version

**Comment by EvanDylan** [comment]
time to support kong 0.10.0 version

**Comment by linonetwo** [comment]
seems fixed?

**Comment by iver3on** [comment]
0.13.1  same error what's wrong

**Comment by 24kpure** [comment]
0.14.0 same error ,sad
