### ISSUE TITLE
OAuth is enabled for all APIs/Consumers

### ISSUE THREAD

**Issue by agopal128** [PGBI/kong-dashboard#84]
Using the Kong Dashboard, if OAuth is enabled for 1 API/Consumer, it is enabled for all APIs/Consumers.

Need the ability to enable OAuth for select consumers instead of all consumers

**Comment by PGBI** [comment]
That should be a request for Kong, not Kong-Dashboard. But I doubt they'll do it. By definition, an authentication plugin can't be applied to one Consumer. You would still need to authenticate all consumers to know which one to authenticate...
