### ISSUE TITLE
Add option letting Kong-Dashboard connect to a Kong node protected with key-auth

### ISSUE THREAD

**Issue by BetaGrumm** [PGBI/kong-dashboard#87]
I'm trying add key auth to our /admin endpoint (proxys to localhost:8001).
The key auth works fine, but it prevents logging into the kong admin through the dashboard. 

I can still log into the dashboard with basic auth, but when I get to the Kong node configuration page, it asks for the kong node url as usual, I paste in the url to the admin as usual, but can't auth regardless if I add the api key in the url or not.
I can't find any other options to enable the dashboard to use key auth for the node configuration.

Am I just missing something or is this expected?

**Comment by PGBI** [comment]
So for the late answer. No, there is no way to configure Kong-Dashboard so that it can reach a Kong node protected with key-auth. Only basic-auth is supported for now. That's something we need to support.
