### ISSUE TITLE
"Strip request path" setting cannot be undone

### ISSUE THREAD

**Issue by DonMartin76** [PGBI/kong-dashboard#9]
When adding/updating an API, once you have set the "Strip request path" property of the API, you cannot undo it.

**Steps to reproduce**:
1. Create an API, check the "Strip request path" checkbox, save
2. Update the same API, uncheck the "Strip request path" checkbox, save
3. Click "Edit" for the same API again.

**Result**: The checkbox "Strip request path" is still set.

**Expected**: The checkbox is unchecked.

**Comment by PGBI** [comment]
Thanks for reporting! I'll have a look.

**Comment by PGBI** [comment]
This is actually a kong bug, and not a kong-dashboard one. I filled an issue on kong repository: https://github.com/Mashape/kong/issues/765

**Comment by PGBI** [comment]
This bug is now fixed if you upgrade to kong 0.6.0.
