### ISSUE TITLE
Can't connect to Kong server. ERROR

### ISSUE THREAD

**Issue by newasmod** [PGBI/kong-dashboard#90]
I am runnining docker-compose KONG from this repo `https://github.com/Mashape/docker-kong/tree/master/compose` and trying to run this great repo in docker too. I provided 0.0.0.0:8001 in node URL but got error : 'Can't connect to Kong server.' ... curl 0.0.0.0:8001 responds fine ...
I am using `Linux Mint 18.1 Serena`

![](https://cloud.githubusercontent.com/assets/25117623/24848624/4eac20e0-1dd0-11e7-905e-ebe61e080118.png)

**Comment by PGBI** [comment]
0.0.0.0 might be a valid address for your host machine, but it is not for the docker container. If Kong is running on your host machine, you must indicate the IP of your host machine (for instance 192.168.1.1).

**Comment by newasmod** [comment]
@PGBI You meant machine address in network? I have set my network `IPv4 Address` nad its work . Thank you!
