### ISSUE TITLE
v2 docker image: write EPIPE error

### ISSUE THREAD

**Issue by hanselke** [PGBI/kong-dashboard#97]
2017-5-3 16:47:17
2017-5-3 16:47:17> kong-dashboard@1.3.1 start /app
2017-5-3 16:47:17> node ./bin/kong-dashboard start
2017-5-3 16:47:17
2017-5-3 16:47:18Launching webserver
2017-5-3 16:47:18Server is running on port 8080
2017-5-3 16:54:08
2017-5-3 16:54:08  Error: write EPIPE
2017-5-3 16:54:08      at exports._errnoException (util.js:1023:11)
2017-5-3 16:54:08      at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
2017-5-3 16:54:08

**Comment by PGBI** [comment]
I'll need more context to start debugging that. I don't understand if you get this on container startup or on image build, I don't see what was the command you issued, etc.
