### ISSUE TITLE
What is the latest version for kong-dashboard 1.x.x?

### ISSUE THREAD

**Issue by fysheets** [PGBI/kong-dashboard#98]
I didn't realize that Kong 0.10.x was already released, I ran an update on my kong-dashboard and it automatically updated to a 2.x.x version and I'm not yet ready to upgrade to the newest version of Kong as it has breaking changes.  I'd like to update my npm installed version of the dashboard to the lastest kong-dashboard that will work with our 0.9.x Kong version.  I couldn't find in the documentation what the highest level 1.x.x version available was for the dashboard.  Thanks!

**Comment by fysheets** [comment]
Looks like it's 1.3.1 - just want to confirm that the jump was from that to 2.0.0 - thanks!

**Comment by PGBI** [comment]
Yep, 1.3.1. You can checkout the homepage, there is a compatibility matrix telling which versions of kong-dashboard are compatible with a given version of Kong.

**Comment by fysheets** [comment]
Thank you!
